// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AlbamModalController from "./albam_modal_controller"
application.register("albam-modal", AlbamModalController)

import ClearCommentController from "./clear_comment_controller"
application.register("clear-comment", ClearCommentController)

import CommentModalController from "./comment_modal_controller"
application.register("comment-modal", CommentModalController)

import ModalController from "./modal_controller"
application.register("modal", ModalController)

import PreviewController from "./preview_controller"
application.register("preview", PreviewController)

import QuestionController from "./question_controller"
application.register("question", QuestionController)

import RemovalsController from "./removals_controller"
application.register("removals", RemovalsController)

import SliderController from "./slider_controller"
application.register("slider", SliderController)
