// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import CommentModalController from "./comment_modal_controller"
application.register("comment-modal", CommentModalController)

import ModalController from "./modal_controller"
application.register("modal", ModalController)

import PopoverController from "./popover_controller"
application.register("popover", PopoverController)

import PreviewController from "./preview_controller"
application.register("preview", PreviewController)

import RemovalsController from "./removals_controller"
application.register("removals", RemovalsController)

import SliderController from "./slider_controller"
application.register("slider", SliderController)
