// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AlbumsliderController from "./albumslider_controller"
application.register("albumslider", AlbumsliderController)

import CardsliderController from "./cardslider_controller"
application.register("cardslider", CardsliderController)

import CommentModalController from "./comment_modal_controller"
application.register("comment-modal", CommentModalController)

import PreviewController from "./preview_controller"
application.register("preview", PreviewController)

import RemovalsController from "./removals_controller"
application.register("removals", RemovalsController)

import SliderController from "./slider_controller"
application.register("slider", SliderController)
